version: 2

# Defining groups https://docs.getdbt.com/docs/build/groups
groups:
  - name: finance
    owner:
      # 'name' or 'email' is required; additional properties allowed
      email: finance@jaffleshop.com
      slack: finance-data
      github: finance-data-team
  - name: customer_success
    owner:
      # 'name' or 'email' is required; additional properties allowed
      email: customer_success@jaffleshop.com
      slack: customer-success
      github: customer-success-data-team

models:
  - name: dim_customers
    description: Represents one unique customer per row
    access: public
    config:
      group: customer_success
      contract: # https://docs.getdbt.com/reference/resource-properties/constraints
        enforced: true
        alias_type: true # it is true by default, added as reminder
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null
        # contract start
        data_type: int
        constraints:
          - type: not_null
          - type: primary_key # will get warning in logs as not enforced by bigquery
          - type: check
            expression: "id > 0"
      - name: first_name
        data_type: text
      - name: last_name
        data_type: text
      - name: first_order_date
        data_type: date
      - name: most_recent_order_date
        data_type: date
      - name: number_of_orders # you can skip one column to see contract violation
        data_type: int
      - name: lifetime_value
        data_type: float # saying int will fail the contract says int but value is float
        # contract end
    # versioning start
    latest_version: 1
    versions:
      - v: 2
      - v: 1
        config:
          alias: dim_customers
        columns:
          - include: "*"
            exclude:
              - lifetime_value
    # versioning end


  - name: fct_orders
    access: public
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: customer_id
        tests:
          - not_null


  - name: stg_jaffle_shop__customers
    description: Represents one unique customer per row from the source
    access: private
    columns:
      - name: customer_id
        description: This is the primary key
        tests:
          - unique
          - not_null


  - name: stg_jaffle_shop__orders
    description: Represents one order per row
    access: protected # this is used in the finance fct_orders
    columns:
      - name: order_id
        description: This is the primary key
        tests: # check the logs to see the compiled sql query created for the tests
          - unique
          - not_null
      - name: status
        description: "{{ doc('order_status')}}"
        tests:
          - accepted_values:
              values:
                ["placed", "shipped", "completed", "return_pending", "returned"]
      - name: customer_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_jaffle_shop__customers')
              field: customer_id


  - name: stg_stripe__payments
    access: private
    config:
      group: finance # this config will override what is there in dbt_project.yml i.e. project level
    columns:
      - name: payment_id
        tests:
          - unique
          - not_null
      - name: order_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_jaffle_shop__orders')
              field: order_id
      - name: status
        tests:
          - accepted_values:
              values: ["success", "fail"]
